### ISSUE TITLE
Add max_instance_lifetime to Web ASG

### ISSUE THREAD

**Issue by joeds13** [joeds13/aws-concourse#21]
Ensures web nodes are rotated, pick up new patched AMIs

resource/aws_autoscaling_group: Add max_instance_lifetime argument (#10951)

**Comment by draagc-iw** [comment]
Would 24 hours be a good default for max_instance_lifetime? @joeds13

**Comment by draagc-iw** [comment]
Terraform is throwing an error:
```
Error: Unsupported argument

  on ../modules/concourse_web/asg.tf line 6, in resource "aws_autoscaling_group" "web":
   6:   max_instance_lifetime = 60 * 60 * 24

An argument named "max_instance_lifetime" is not expected here.
```
... even though the argument is listed in the documentation for [aws_autoscaling_group](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html). Not listed as an input on the actual [terraform module](https://github.com/terraform-aws-modules/terraform-aws-autoscaling)

**Comment by joeds13** [comment]
I think 24 hours is a little quick to refresh, the idea is to capture new versions from a scheduled AMI building process. So my initial thoughts was maybe 3 days?

Did you run an `terraform init -upgrade` and ensure you were on version `2.41.0` of the provider?
https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2410-december-04-2019

**Comment by draagc-iw** [comment]
That fixed it, my bad. The minimum you can set for max_instance_lifetime is 7 days so I'll go with that
